
const colors = {
//navigationbar
	NAVBAR_BACKGROUND: '#D10909',
	NAVBAR_TEXT: 'white',
	NAVBAR_BUTTON: 'white',
	STATUSBAR_BACKGROUND: '#B10101',
	CONTAINER_BACKGROUND: '#E9E9E9',
	SETTING_BACKGROUND: 'white',

//slidemenu 
	BORDER: '#CCC',
	USER_VIEW: '#D10909',
	USER_IMG: 'white',
	USER_TEXT: 'white',
	MENU_BACKGROUND: 'white',
	ITEMS_ICON: '#FF7878',

//combination list
	PUZZLE_BACK: '#BEBEBE',
	COMBINATION_ROW: 'white',
	COMBINATION_ROWBACK: 'lightgrey',
	ROWBACK_BUTTON: '#525252',
	NO_CONBINATION: '#B6B6B6',

//buttonlist
	BUTTONLIST_BACKGROUND: 'white',
	MINBUTTONLIST_BACKGROUND: 'white',
	SHADOW_BACKGROUND: 'lightgrey',
	BOTTOM_BACKGROUND: 'white',
	MINBUTTON: ['white', '#B7B7B7', '#D3D3D3', 'white'],
	ON_MINBUTTON: ['#B7B7B7', 'white', 'white', '#D3D3D3'],
	BOTTOM_VIEW: ['black', 'black', 'black', 'white'],

//config button
	DISABLE_BUTTON: '#969696',

	BUTTON_DISABLED_BORDER: '#B2B6B2',
	BUTTON_UNDEFIND_BORDER: '#FF7878',
	BUTTON_BORDER: 'white',

	BUTTON_UNDEFIND_BACKGROUND: 'white',
	BUTTON_BACKGROUND: '#FF7878',

	BUTTON_DISABLED_TEXT: '#B2B6B2',
	BUTTON_UNDEFIND_TEXT: '#FF7878',
	BUTTON_TEXT: 'white',

//GradientButton
	BUTTON_POSTURE: '#D10909',

//trigger,action setting
	NO_SETTING_TEXT: '#499275',
	INPUT_BORDER: '#B2B6B2',

	SUBMIT: '#59d059',
	SETTING_SUBMIT: '#FF7878',

//ponitor record
	START_BUTTON: '#15D900',

  SCANNING_BACKGROUND: '#42B9F4',
  SCANNING_TIPS_BACKGROUND: '#e5fbfc',
  
	WHITE_TEXT: '#FFFFFF',
	SIGNUP_SUBMIT: '#269be7',
	ERROR_TEXT: '#e93a5c'

};

export default colors;
