const colors = {
	NAVBAR_BACKGROUND: '#3FA9F5',
	NAVBAR_TEXT: 'white',
	NAVBAR_BUTTON: 'white',
	STATUSBAR_BACKGROUND: '#2F7FB8',
	CONTAINER_BACKGROUND: '#E9E9E9',
	SETTING_BACKGROUND: 'white',

	DISABLE_BUTTON: '#969696',

	PUZZLE_BACK: '#BEBEBE',
	COMBINATION_ROWBACK: 'lightgrey',

	BUTTON_DISABLED_BORDER: '#B2B6B2',
	BUTTON_UNDEFIND_BORDER: '#3FA9F5',
	BUTTON_BORDER: 'white',

	BUTTON_UNDEFIND_BACKGROUND: 'white',
	BUTTON_BACKGROUND: '#3FA9F5',

	BUTTON_DISABLED_TEXT: '#B2B6B2',
	BUTTON_UNDEFIND_TEXT: '#3FA9F5',
	BUTTON_TEXT: 'white',
	
	SUBMIT: '#59d059',

	INPUT_BORDER: '#B2B6B2'
};

export default colors;
