const colors = {
//navigationbar
	NAVBAR_BACKGROUND: '#0084E2',
	NAVBAR_TEXT: 'white',
	NAVBAR_BUTTON: 'white',
	STATUSBAR_BACKGROUND: '#1273B8',
	CONTAINER_BACKGROUND: '#E9E9E9',
	SETTING_BACKGROUND: 'white',

//slidemenu 
	BORDER: '#CCC',
	USER_VIEW: '#28A4FC',
	USER_IMG: 'white',
	USER_TEXT: 'white',
	MENU_BACKGROUND: 'white',

//combination list
	PUZZLE_BACK: '#BEBEBE',
	COMBINATION_ROW: 'white',
	COMBINATION_ROWBACK: 'lightgrey',

//addcombination setting button
	DISABLE_BUTTON: '#969696',

	BUTTON_DISABLED_BORDER: '#B2B6B2',
	BUTTON_UNDEFIND_BORDER: '#3FA9F5',
	BUTTON_BORDER: 'white',

	BUTTON_UNDEFIND_BACKGROUND: 'white',
	BUTTON_BACKGROUND: '#3FA9F5',

	BUTTON_DISABLED_TEXT: '#B2B6B2',
	BUTTON_UNDEFIND_TEXT: '#3FA9F5',
	BUTTON_TEXT: 'white',

//trigger,action setting
	NO_SETTING_TEXT: '#499275',
	INPUT_BORDER: '#B2B6B2',

	SUBMIT: '#59d059',
	SETTING_SUBMIT: '#2aceba',


	INPUT_BORDER: '#B2B6B2',

  SCANNING_BACKGROUND: '#42B9F4',
  SCANNING_TIPS_BACKGROUND: '#e5fbfc'
};

export default colors;
