# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
use_frameworks!

target 'posture_linking' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for posture_linking
  pod 'Firebase/Core'
  pod 'SwiftyJSON', '3.1.4'
  pod 'Charts', :tag => 'v3.0.2', :git => 'https://github.com/danielgindi/Charts.git'

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
